---
# Configuration file for CML jobs
# Contains all job definitions and their parameters

jobs:
  create_env:
    name: Create Python Environment
    script: fraud-cloudera/cloudera-fraud-detection/create_environment.py
    kernel: python3
    runtime_id: docker.repository.cloudera.com/cloudera/cdsw/ml-runtime-pbj-jupyterlab-python3.10-standard:2025.01.2-b15
    cpu: 1
    memory: 2
    timeout: 1800  # 30 minutes
    environment: {}
    arguments: ""

  feature_engineering:
    name: Feature Engineering for Fraud Detection
    script: fraud-cloudera/cloudera-fraud-detection/scripts/run_feature_engineering.py
    kernel: python3
    runtime_id: docker.repository.cloudera.com/cloudera/cdsw/ml-runtime-pbj-jupyterlab-python3.10-standard:2025.01.2-b15
    cpu: 2
    memory: 4
    timeout: 1800  # 30 minutes
    environment: {}
    arguments: ""

  train_model:
    name: Train LightGBM Fraud Detection Model
    script: fraud-cloudera/cloudera-fraud-detection/scripts/run_train_model.py
    kernel: python3
    runtime_id: docker.repository.cloudera.com/cloudera/cdsw/ml-runtime-pbj-jupyterlab-python3.10-standard:2025.01.2-b15
    cpu: 4
    memory: 8
    timeout: 3600  # 60 minutes
    environment: {}
    arguments: ""
    dependencies:
      - feature_engineering

  score_transactions:
    name: Score Last Year Transactions
    script: fraud-cloudera/cloudera-fraud-detection/scripts/run_score_transactions.py
    kernel: python3
    runtime_id: docker.repository.cloudera.com/cloudera/cdsw/ml-runtime-pbj-jupyterlab-python3.10-standard:2025.01.2-b15
    cpu: 2
    memory: 4
    timeout: 1800  # 30 minutes
    environment: {}
    arguments: ""
    dependencies:
      - train_model

  deploy_model:
    name: Deploy Fraud Detection Model to CML
    script: fraud-cloudera/cloudera-fraud-detection/deploy_model.py
    kernel: python3
    runtime_id: docker.repository.cloudera.com/cloudera/cdsw/ml-runtime-pbj-jupyterlab-python3.10-standard:2025.01.2-b15
    cpu: 1
    memory: 2
    timeout: 2700  # 45 minutes
    environment: {}
    arguments: ""
    dependencies:
      - train_model

